# Generated by Django 3.1.3 on 2020-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_company_post_post_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_detail',
            name='kyodo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
