# Generated by Django 3.1.3 on 2020-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201105_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_detail',
            name='duedate',
            field=models.DateTimeField(null=True),
        ),
    ]
